language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl

install:
  - sudo apt-get install info install-info
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^#cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi
  - cl -l alexandria -l clx -l cl-ppcre -e '(ql-util:without-prompting (ql:add-to-init-file))'

before_script:
  - ./autogen.sh
  - ./configure

script:
  - make travis
