language: lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=clisp
    # - LISP=ecl

install:
  - sudo apt-get install texinfo
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^#cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi
  - install_cl_launch
  - cl-launch -i '(ql:quickload "clx")' -i '(ql:quickload "cl-ppcre")'

before_script:
  - ./autogen.sh
  - ./configure

script:
  - make
